export const routes = {
  home: '/',
  product: '/product',
  contact: '/contact',
  healthcareProviders: '/healthcare-providers',
  forConciergeMedicine: '/for-concierge-medicine',
  forEmployers: '/for-employers',
  heartAmbassadors: '/heart-ambassadors',
  science: '/science',
  blog: '/blog',
  news: '/news',
  team: '/team',
  termsConditions: '/terms-conditions',
  privacyPolicy: '/privacy-policy',
  investorsSecFilings: '/investors-sec-filings',
  analystCoverage: '/analyst-coverage',
  healthPlans: '/health-plans',
  womensHealth: '/womens-health',
  eventsBeckersWebinar: '/events-beckers-webinar',
  videos: '/videos',
}
