export const routes = {
  home: '/',
  product: '/product',
  contact: '/contact',
  healthcareProviders: '/healthcare-providers',
  science: '/science',
  blog: '/blog',
  analystCoverage: '/analyst-coverage',
  healthPlans: '/health-plans',
  videos: '/videos',
  epigenChd: '/epigen-chd',
  precisionChd: '/precision-chd',
  healthCareProviders: '/health-care-providers',
  employers: '/employers',
  healthcareSystems: '/healthcare-systems',
  publicSector: '/public-sector',
  pharma: '/pharma',
  lifeInsurance: '/life-insurance',
  overview: '/overview',
  events: '/events',
  help: '/help',
  secFilings: '/sec-filings',
  pressReleases: '/press-releases',
  corporateOverview: '/corporate-overview',
}
